global flipYZ = true
global flipYZ_transform = matrix3 [1,0,0] [0,0,-1] [0,1,0] [0,0,0] -- matrix to transform to default opengl axis

global exportMeshes = true
global exportMaterials = true
global exportSkins = true

global customAnimName = false

global formattedPrintFormat = ".6g"

global compressJson = false

global TAB = 0

global TAB_ARRAY = #( "\t" )

global nl = ""

global cnl = ","

global sp = ""
